# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import prosemirror.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('slug', models.SlugField()),
                ('abstract', models.TextField()),
                ('body', prosemirror.fields.ProseMirrorField()),
            ],
        ),
    ]
